name: Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout OpenActive.DatasetSite.NET
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET 8.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./OpenActive.DatasetSite.NET.Tests/OpenActive.DatasetSite.NET.Tests.csproj --no-restore --configuration Release
    - name: Test
      run: dotnet test ./OpenActive.DatasetSite.NET.Tests/OpenActive.DatasetSite.NET.Tests.csproj --configuration Release --no-restore --no-build --verbosity normal
